#!/bin/sh

berryc border_width 0
berryc inner_border_width 0
berryc title_height 40
berryc focus_color 292d3e
berryc unfocus_color 292d3e
berryc inner_focus_color b89ca8
berryc inner_unfocus_color 343d41
berryc text_focus_color 2c3539
berryc text_unfocus_color 565679
berryc set_font    "DinaTTF-9"
