#!/bin/sh
#
# $OpenBSD: Xsession.in,v 1.2 2022/07/01 20:42:06 naddy Exp $
prefix="/usr/X11R6"
exec_prefix="${prefix}"

errfile="/tmp/.xsession-errors"
if ( umask 077 && cp /dev/null "$errfile" 2> /dev/null )
then
	exec > "$errfile" 2>&1
else
	for errfile in "${TMPDIR-/tmp}/xses-$USER" "/tmp/xses-$USER"
	do
		if ef="$( umask 077 && mktemp "$errfile.XXXXXX" 2> /dev/null)"
		then
			exec > "$ef" 2>&1
			mv "$ef" "$errfile" 2> /dev/null
			break
		fi
	done
fi

startup=$HOME/rules/xsession
resources=$HOME/rules/Xresources
id=$HOME/.ssh/id_ed25519

if [ -z "$SSH_AGENT_PID" ];
then
	if [ -x /usr/bin/ssh-agent ] && [ -f $id ];
	then
		eval `ssh-agent -s`
		ssh-add < /dev/null
	fi
fi

if [ -s "$startup" ]; then
	if [ -x "$startup" ]; then
		"$startup"
	else
		/bin/sh "$startup"
	fi
else
	if [ -f "$resources" ]; then
		/usr/X11R6/bin/xrdb -load "$resources"
	fi
	${exec_prefix}/bin/xterm &
	${exec_prefix}/bin/fvwm
fi
do_exit
